### ISSUE TITLE
Checksum error on cargo on s390x

### ISSUE THREAD

**Issue by fabiocosta0305** [remram44/adler32-rs#23]
Trying to use adler32 for building InfluxDB on s390x...

Got this message

   Executing cargo build	{"dir": "/root/.cache/go-build/pkgconfig/github.com/influxdata/flux@v0.193.0   /libflux", "target": "s390x-unknown-linux-gnu"}
    Downloading crates ...
     Downloaded adler32 v1.2.0
   error: failed to verify the checksum of `adler32 v1.2.0`

**Comment by remram44** [comment]
Is it possible you have a tool chain problem, and adler33 fails first because it is tried first since it is first alphabetically? There is no reason this should fail.
