### ISSUE TITLE
remove() panics when size > BASE

### ISSUE THREAD

**Issue by Deewiant** [remram44/adler32-rs#4]
The subtraction in `RollingAdler32::remove` panics when `size > BASE` i.e. `size > 65521`:

```
panicked at 'attempt to subtract with overflow', src/lib.rs:289
```

Changing that to allow wrapping causes more panics. Things seem to work alright once the subtraction, multiplication, and addition are changed to their wrapping equivalents, i.e.:

```rust
self.b = ((self.b + BASE - 1).wrapping_add(BASE.wrapping_sub(size as u32).wrapping_mul(byte))) % BASE;
```

---

As a side note it's also nasty that `size` is taken as `usize` in the API but immediately reduced to `u32`. If extending the calculation to `usize` is not an option then it'd be better if the interface were honest...

**Comment by remram44** [comment]
I released version `1.0.1`
